

name: build rt-k3-mainline
permissions:
  contents: write
on: 
  workflow_dispatch:
    inputs:
      eth0:
        description: 'Your Eth0 Mac'
        required: true
        default: '00:11:22:33:44:55'
      Wlan0:
        description: 'Your Eth1(2.4g) Mac'
        required: true
        default: '00:11:22:33:44:66'
      Wlan1:
        description: 'Your Eth2(5g) Mac'
        required: true
        default: '00:11:22:33:44:77'
  release:
    types: [published]
  push:
    tags:
    - 'v*'
#  branches: 
#    - master
#  schedule:
#    - cron: 0 8 * * 5
    
env:
  ET0MACADDR: github.event.inputs.eth0     
  MACADDR1_24G: github.event.inputs.Wlan0
  MACADDR2_5G: github.event.inputs.Wlan1
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-20.04
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Update && install packages
      run: |
        sudo apt-get update
        # ... (Install the rest of your packages)
    - name: Fix aclocal error
      run: |
        # ... (Your aclocal fix steps if needed)
    - name: Update x86 package
      run: |
        sudo dpkg --print-foreign-architectures
        sudo apt-get update
        sudo apt-get install -y libc6-i386 lib32stdc++6 lib32z1 libelf1:i386 lib32ncurses5-dev libc6-dev-i386
    - name: Clone source code
      run: |       
        git clone https://github.com/RMerl/asuswrt-merlin.ng
        # ... (Clone other repositories)
        sudo mkdir -p /media/asuswrt/
        sudo mkdir -p /opt/images/
    - name: Link Directory
      run: |       
        sudo ln -s $(pwd)/am-toolchains/brcm-arm-hnd /opt/toolchains
        sudo ln -s $(pwd)/am-toolchains/brcm-arm-sdk/hndtools-arm-linux-2.6.36-uclibc-4.5.3 /opt/brcm-arm
        sudo ln -sf bash /bin/sh
        echo "export LD_LIBRARY_PATH=$LD_LIBRARY:/opt/toolchains/crosstools-arm-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/lib" >> ~/.profile
        echo "export TOOLCHAIN_BASE=/opt/toolchains" >> ~/.profile
        echo "PATH=\$PATH:/opt/toolchains/crosstools-arm-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin" >> ~/.profile
        echo "PATH=\$PATH:/opt/toolchains/crosstools-aarch64-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin" >> ~/.profile
        sudo ln -s $(pwd)/asuswrt-merlin.ng /media/asuswrt/asuswrt-merlin.ng
    - name: Update repository and checkout branch
      run: |
        cd /media/asuswrt/asuswrt-merlin.ng
        git fetch origin
        git checkout main # Assuming "main" is the main development branch
        echo "::set-env name=MERLIN_VERSION::$(git show-ref --heads -s)"
        echo "::set-env name=MERLIN_TAG::$(git show-ref --heads --hash=8)"
        echo "::set-env name=BUILD_DATE::$(date +%Y%m%d%H%M)"
    - name: Modify File
      run: |        
        cd  /media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/src/cfe/build/broadcom/bcm947xx/compressed
        echo "replace mac address from $(cat rt-k3_nvram.txt | grep ^et0macaddr) to ${{ env.ET0MACADDR }}"
        sed -i 's/^\(et0macaddr=\).*/\1${{ env.ET0MACADDR }}/g' rt-k3_nvram.txt
        echo "replace mac 2.4g address from $(cat rt-k3_nvram.txt | grep ^1:macaddr) to ${{ env.MACADDR1_24G }}"
        sed -i 's/^\(1:macaddr=\).*/\1${{ env.MACADDR1_24G }}/g' rt-k3_nvram.txt
        echo "replace mac 5g address from $(cat rt-k3_nvram.txt | grep ^2:macaddr) to ${{ env.MACADDR2_5G }}"
        sed -i 's/^\(2:macaddr=\).*/\1${{ env.MACADDR2_5G }}/g' rt-k3_nvram.txt
    - name: Build Firmware
      run: |
        #export PATH=$PATH:/opt/brcm/hndtools-mipsel-linux/bin:/opt/brcm/hndtools-mipsel-uclibc/bin:
        export PATH=$PATH:/opt/brcm-arm/bin
        cd  /media/asuswrt/asuswrt-merlin.ng/release/src-rt
        echo "add tag to version"
        sed -i 's/EXTENDNO=.*/&_${{ env.MERLIN_TAG }}/g' version.conf
        cd /media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/src
        make rt-k3
        echo "build image done"     
        cd /media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/src/cfe/
        make
        echo "build cfe done"
    - name: Move file && Checksum
      run: |
        sudo mv -f /media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/src/image/*.trx /opt/images/
        sudo cp /media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/src/cfe/build/broadcom/bcm947xx/compressed/rt-k3_nvram.txt /opt/images/
        sudo cp /media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/src/cfe/cfe*.bin /opt/images/
        sha256sum /opt/images/* > /opt/images/checksum.txt
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: "/opt/images/*.*,release/src-rt-7.14.114.x/src/cfe/cfe_rt-k3.bin"  
        tag_name: ${{ env.BUILD_DATE }}_mainline_k3_${{ env.MERLIN_TAG }}
        body: |
          this is only a latest build from mainline
          version: https://github.com/godcong/asuswrt-merlin.ng/commit/${{ env.MERLIN_VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
