name: build rt-k3-mainline
permissions:
  contents: write
on: 
  workflow_dispatch:
    inputs:
      eth0:
        description: 'Your Eth0 Mac'
        required: true
        default: '00:11:22:33:44:55'
      Wlan0:
        description: 'Your Eth1(2.4g) Mac'
        required: true
        default: '00:11:22:33:44:66'
      Wlan1:
        description: 'Your Eth2(5g) Mac'
        required: true
        default: '00:11:22:33:44:77'
  release:
    types: [published]
  push:
    tags:
    - 'v*'
    
env:
  ET0MACADDR: ${{ github.event.inputs.eth0 }}
  MACADDR1_24G: ${{ github.event.inputs.Wlan0 }}
  MACADDR2_5G: ${{ github.event.inputs.Wlan1 }}
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
    defaults:
      run:
        shell: bash   
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup environment
      run: |
        apt-get update
        DEBIAN_FRONTEND=noninteractive apt-get install -y tzdata
        apt-get install -y software-properties-common bash
        add-apt-repository universe
        apt-get update
        apt-get install -y git wget curl build-essential libncurses5-dev libncursesw5-dev \
        zlib1g-dev gawk gettext libssl-dev xsltproc rsync gcc-multilib \
        u-boot-tools mtd-utils device-tree-compiler \
        libtool-bin cmake libproxy-dev uuid-dev liblzo2-dev autoconf automake \
        bash bison bzip2 diffutils file flex g++ gperf grep groff-base \
        libc6-dev libexpat1-dev libffi-dev libncurses5-dev libsigsegv2 \
        libslang2 libssl-dev libtool libxml-parser-perl make patch perl pkg-config \
        python sed shtool tar texinfo unzip zlib1g zlib1g-dev
        
        # Install cross-compilation toolchain
        apt-get install -y gcc-mipsel-linux-gnu
        
        # Install additional dependencies
        apt-get install -y libelf-dev
        

    - name: Clone source code
      run: |       
        git clone https://github.com/godcong/asuswrt-merlin.ng
        git clone https://github.com/godcong/k3screenctrl asuswrt-merlin.ng/release/src/router/k3screenctrl 
        git clone https://github.com/RMerl/am-toolchains.git
        
        mkdir -p /media/asuswrt/
        mkdir -p /opt/images/
        
        ln -sf $(pwd)/asuswrt-merlin.ng /media/asuswrt/asuswrt-merlin.ng       
        
        cd /media/asuswrt/asuswrt-merlin.ng
        git checkout mainline    
        echo "MERLIN_VERSION=$(git show-ref --heads -s)" >> $GITHUB_ENV
        echo "MERLIN_TAG=$(git show-ref --heads --hash=8)" >> $GITHUB_ENV
        echo "BUILD_DATE=$(date +%Y%m%d%H%M)" >> $GITHUB_ENV

    - name: Setup build environment
      run: |
        cd /media/asuswrt/asuswrt-merlin.ng || exit 1
        
        ln -sf $(pwd)/am-toolchains/brcm-arm-hnd /opt/toolchains
        ln -sf $(pwd)/am-toolchains/brcm-arm-sdk/hndtools-arm-linux-2.6.36-uclibc-4.5.3 /opt/brcm-arm
        
        echo "export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/opt/toolchains/crosstools-arm-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/lib" >> ~/.bashrc
        echo "export PATH=$PATH:/opt/toolchains/crosstools-arm-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin:/opt/brcm-arm/bin" >> ~/.bashrc
        
        . ~/.bashrc
        
        echo "Current directory: $(pwd)"
        echo "PATH: $PATH"
        echo "LD_LIBRARY_PATH: $LD_LIBRARY_PATH"
        ls -l /opt/toolchains || echo "Directory /opt/toolchains does not exist"
        ls -l /opt/brcm-arm || echo "Directory /opt/brcm-arm does not exist"
        
        which mipsel-linux-gnu-gcc || echo "mipsel-linux-gnu-gcc not found in PATH"
    - name: Modify File
      run: |
        cd /media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/src/cfe/build/broadcom/bcm947xx/compressed
        echo "replace mac address from $(grep ^et0macaddr rt-k3_nvram.txt) to ${{ env.ET0MACADDR }}"
        sed -i 's/^et0macaddr=.*/et0macaddr=${{ env.ET0MACADDR }}/g' rt-k3_nvram.txt
        echo "replace mac 2.4g address from $(grep ^1:macaddr rt-k3_nvram.txt) to ${{ env.MACADDR1_24G }}"
        sed -i 's/^1:macaddr=.*/1:macaddr=${{ env.MACADDR1_24G }}/g' rt-k3_nvram.txt
        echo "replace mac 5g address from $(grep ^2:macaddr rt-k3_nvram.txt) to ${{ env.MACADDR2_5G }}"
        sed -i 's/^2:macaddr=.*/2:macaddr=${{ env.MACADDR2_5G }}/g' rt-k3_nvram.txt
        
        echo "Modified content:"
        grep -E '^(et0macaddr|1:macaddr|2:macaddr)' rt-k3_nvram.txt

    - name: Prepare Configuration
      run: |
        cd /media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/src
    
        # 设置环境变量
        export PATH=$PATH:/opt/brcm-arm/bin:/opt/toolchains/crosstools-arm-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin
        export STAGING_DIR=/media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/src/staging_dir
        export BUILD_NAME=RT-K3
        export OPENSSLDIR=/usr/lib/ssl
        export CONFIGURE_ARGS="--with-openssl=$OPENSSLDIR"
    
        # 创建 .config 文件
        cat << EOF > .config
        CONFIG_BCMWL5=y
        CONFIG_BCMWL6=y
        CONFIG_BCM7=y
        CONFIG_BCMARM=y
        CONFIG_RT_K3=y
        CONFIG_RTCONFIG_HTTPS=y
        CONFIG_RTCONFIG_SSH=y
        CONFIG_RTCONFIG_BCMARM=y
        CONFIG_RTCONFIG_OPENSSL11=y
        EOF
    
        # 创建一个空的 save-config 文件
        touch save-config
    
        # 检查并修改 router/Makefile
        ROUTER_MAKEFILE="../router/Makefile"
        if [ -f "$ROUTER_MAKEFILE" ]; then
          echo "Contents of router/Makefile around line 478:"
          sed -n '473,483p' "$ROUTER_MAKEFILE"
      
          # 尝试修复 OpenSSL 定义
          sed -i 's/^ifeq ($(OPENSSL),y)/ifeq ($(RTCONFIG_HTTPS)$(RTCONFIG_SSH),yy)/' "$ROUTER_MAKEFILE"
      
          echo "Modified contents of router/Makefile around line 478:"
          sed -n '473,483p' "$ROUTER_MAKEFILE"
        else
          echo "router/Makefile not found"
        fi
    
        # 验证配置
        echo "Environment variables:"
        env | grep -E "PATH|STAGING_DIR|BUILD_NAME|OPENSSL"
    
        echo "Config file contents:"
        cat .config
        
        # 检查关键文件和目录
        echo "Checking key files and directories:"
        ls -l .config save-config ../router/Makefile
    
        # 尝试运行 make setprofile 命令并显示详细输出
        echo "Testing make setprofile command:"
        make -n setprofile
    
        echo "Running make setprofile with verbose output:"
        make setprofile V=s

    - name: Build Firmware
      run: |
          cd /media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/src
    
          # 重新设置环境变量，以确保它们在新的 shell 中可用
          export PATH=$PATH:/opt/brcm-arm/bin:/opt/toolchains/crosstools-arm-gcc-5.3-linux-4.1-glibc-2.22-binutils-2.25/usr/bin
          export STAGING_DIR=/media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/src/staging_dir
          export BUILD_NAME=RT-K3
          export OPENSSLDIR=/usr/lib/ssl
          export CONFIGURE_ARGS="--with-openssl=$OPENSSLDIR"
    
          make setprofile
          make RT-K3
    
          if [ $? -ne 0 ]; then
            echo "Compilation failed. Showing last 100 lines of error log:"
            tail -n 100 /media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/src/RT-K3.log
          fi
    - name: Move file && Checksum
      run: |
        mv -f /media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/src/image/*.trx /opt/images/
        cp /media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/src/cfe/build/broadcom/bcm947xx/compressed/rt-k3_nvram.txt /opt/images/
        cp /media/asuswrt/asuswrt-merlin.ng/release/src-rt-7.14.114.x/src/cfe/cfe*.bin /opt/images/
        
        sha256sum /opt/images/* > /opt/images/checksum.txt

    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        files: "/opt/images/*.*,release/src-rt-7.14.114.x/src/cfe/cfe_rt-k3.bin"  
        tag_name: ${{ env.BUILD_DATE }}_mainline_k3_${{ env.MERLIN_TAG }}
        body: |
          this is only a latest build from mainline
          version: https://github.com/godcong/asuswrt-merlin.ng/commit/${{ env.MERLIN_VERSION }}
        token: ${{ secrets.GITHUB_TOKEN }}
